services:
  cassandra:
    image: cassandra:latest
    container_name: cassandra
    ports:
      - 9042:9042
    environment:
      - CASSANDRA_USER=admin
      - CASSANDRA_PASSWORD=admin
      - PUID=1000
      - PGID=1000
    volumes:
      - './scripts:/scripts/'
    restart: 'unless-stopped'