services:
  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - './scripts:/scripts/'
    ports:
      - 27017:27017
    restart: 'unless-stopped'